# Import libraries

In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.compose import ColumnTransformer

# Load dataset

In [2]:
filename = 'Churn_Modelling.csv'
path = os.path.join('Volume 1 - Supervised Deep Learning', 
                    'Part 1 - Artificial Neural Networks (ANN)',
                    'Section 4 - Building an ANN',
                     filename)
data = pd.read_csv(path)
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

# Selecting features and labels

In [3]:
X = data.iloc[:, 3:13].values
y = data.iloc[:, 13].values

In [4]:
X[:5]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [5]:
y[:5]

array([1, 0, 1, 0, 0], dtype=int64)

# Encoding categorical data

In [6]:
enc = LabelEncoder()
X[:, 2] = enc.fit_transform(X[:, 2])

In [7]:
ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)

In [8]:
X[:5]

array([[1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [1.0, 0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [1.0, 0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

To avoid ***Dummy Variable*** trap we'll drop the first column. We could also have passed `drop='first'` argument to the `OneHotEncoder(drop='first')`

In [9]:
X = X[:, 1:]

# Train test split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                    test_size=0.2, random_state=0)

# Feature Scaling

In [11]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
X_train.shape

(8000, 11)

In [13]:
X_test.shape

(2000, 11)

In [14]:
classifier = Sequential()

In [15]:
# First Hidden Layer
classifier.add(Dense(units=6, kernel_initializer='uniform',
                    activation='relu', input_dim=11))

In [16]:
# Second Hidden Layer
classifier.add(Dense(units=6, kernel_initializer='uniform',
                    activation='relu'))

In [17]:
# Output Layer
classifier.add(Dense(units=1, kernel_initializer='uniform',
                    activation='sigmoid'))

# Train the model

In [18]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# categorical_crossentropy for multiclass classification

In [19]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
800/800 [==============================] - 1s 899us/step - loss: 0.4981 - accuracy: 0.7958
Epoch 2/100
800/800 [==============================] - 1s 873us/step - loss: 0.4304 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 864us/step - loss: 0.4247 - accuracy: 0.7987
Epoch 4/100
800/800 [==============================] - 1s 864us/step - loss: 0.4187 - accuracy: 0.8231
Epoch 5/100
800/800 [==============================] - 1s 874us/step - loss: 0.4133 - accuracy: 0.8306
Epoch 6/100
800/800 [==============================] - 1s 893us/step - loss: 0.4090 - accuracy: 0.8303
Epoch 7/100
800/800 [==============================] - 1s 865us/step - loss: 0.4057 - accuracy: 0.8324
Epoch 8/100
800/800 [==============================] - 1s 869us/step - loss: 0.4039 - accuracy: 0.8351
Epoch 9/100
800/800 [==============================] - 1s 870us/step - loss: 0.4022 - accuracy: 0.8346
Epoch 10/100
800/800 [==============================] - 1s 865us/step - l

800/800 [==============================] - 1s 908us/step - loss: 0.3417 - accuracy: 0.8596
Epoch 81/100
800/800 [==============================] - 1s 893us/step - loss: 0.3421 - accuracy: 0.8605
Epoch 82/100
800/800 [==============================] - 1s 910us/step - loss: 0.3421 - accuracy: 0.8560
Epoch 83/100
800/800 [==============================] - 1s 968us/step - loss: 0.3417 - accuracy: 0.8601
Epoch 84/100
800/800 [==============================] - 1s 979us/step - loss: 0.3422 - accuracy: 0.8574
Epoch 85/100
800/800 [==============================] - 1s 896us/step - loss: 0.3414 - accuracy: 0.8602
Epoch 86/100
800/800 [==============================] - 1s 944us/step - loss: 0.3417 - accuracy: 0.8605
Epoch 87/100
800/800 [==============================] - 1s 865us/step - loss: 0.3427 - accuracy: 0.8610
Epoch 88/100
800/800 [==============================] - 1s 978us/step - loss: 0.3429 - accuracy: 0.8621
Epoch 89/100
800/800 [==============================] - 1s 935us/step - loss:

In [20]:
y_pred = classifier.predict(X_test)

In [21]:
y_pred = (y_pred > 0.5)

In [22]:
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1532   63]
 [ 212  193]]


In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1595
           1       0.75      0.48      0.58       405

    accuracy                           0.86      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000



# New Customer

In [24]:
new_prediction = classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = (new_prediction > 0.5)

In [25]:
new_prediction

array([[False]])

# Improving the model

## k-Fold cross validation
The model has been trained on Keras and the k-Fold Cross Validation belongs to Scikit-Leaern, therefore to combine the functionalitties of both we'll need to use Keras wrapper.

In [26]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [27]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units=6, kernel_initializer='uniform',
                    activation='relu', input_dim=11))
    classifier.add(Dense(units=6, kernel_initializer='uniform',
                    activation='relu'))
    classifier.add(Dense(units=1, kernel_initializer='uniform',
                    activation='sigmoid'))
    classifier.compile(optimizer='adam', loss='binary_crossentropy',
                       metrics=['accuracy'])
    return classifier

In [28]:
classifier = KerasClassifier(build_fn=build_classifier,
                            batch_size=10, nb_epoch=15)

In [29]:
accuracies = cross_val_score(estimator=classifier, X=X_train,
                             y=y_train, cv=10, n_jobs=-1)

In [30]:
accuracies

array([0.78625   , 0.79000002, 0.80000001, 0.78250003, 0.81625003,
       0.81      , 0.78750002, 0.79374999, 0.79874998, 0.79500002])

In [31]:
mean = accuracies.mean()
mean

0.7960000097751617

In [32]:
variance = accuracies.std()
variance

0.010105690527913859

## Tackle overfitting

In [33]:
from keras.layers import Dropout
# Dropout is appplied to neurons so that they are disabled

In [34]:
classifier1 = Sequential()
classifier1.add(Dense(units=6, kernel_initializer='uniform',
                activation='relu', input_dim=11))
classifier1.add(Dropout(0.1)) # p is the fraction of neurons to disable
classifier1.add(Dense(units=6, kernel_initializer='uniform',
                activation='relu'))
classifier1.add(Dropout(0.1))
classifier1.add(Dense(units=1, kernel_initializer='uniform',
                activation='sigmoid'))
classifier1.compile(optimizer='adam', loss='binary_crossentropy',
                   metrics=['accuracy'])
classifier1.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
800/800 [==============================] - 1s 903us/step - loss: 0.4953 - accuracy: 0.7952
Epoch 2/100
800/800 [==============================] - 1s 876us/step - loss: 0.4267 - accuracy: 0.8166
Epoch 3/100
800/800 [==============================] - 1s 911us/step - loss: 0.4199 - accuracy: 0.8185
Epoch 4/100
800/800 [==============================] - 1s 925us/step - loss: 0.4167 - accuracy: 0.8224
Epoch 5/100
800/800 [==============================] - 1s 903us/step - loss: 0.4108 - accuracy: 0.8245
Epoch 6/100
800/800 [==============================] - 1s 910us/step - loss: 0.4061 - accuracy: 0.8214
Epoch 7/100
800/800 [==============================] - 1s 916us/step - loss: 0.4050 - accuracy: 0.8219
Epoch 8/100
800/800 [==============================] - 1s 916us/step - loss: 0.4044 - accuracy: 0.8211
Epoch 9/100
800/800 [==============================] - 1s 921us/step - loss: 0.4026 - accuracy: 0.8234
Epoch 10/100
800/800 [==============================] - 1s 913us/step - l

800/800 [==============================] - 1s 901us/step - loss: 0.3851 - accuracy: 0.8394
Epoch 80/100
800/800 [==============================] - 1s 908us/step - loss: 0.3836 - accuracy: 0.8403
Epoch 81/100
800/800 [==============================] - 1s 893us/step - loss: 0.3883 - accuracy: 0.8421
Epoch 82/100
800/800 [==============================] - 1s 903us/step - loss: 0.3851 - accuracy: 0.8381
Epoch 83/100
800/800 [==============================] - 1s 889us/step - loss: 0.3898 - accuracy: 0.8371
Epoch 84/100
800/800 [==============================] - 1s 880us/step - loss: 0.3860 - accuracy: 0.8384
Epoch 85/100
800/800 [==============================] - 1s 906us/step - loss: 0.3870 - accuracy: 0.8434
Epoch 86/100
800/800 [==============================] - 1s 885us/step - loss: 0.3841 - accuracy: 0.8415
Epoch 87/100
800/800 [==============================] - 1s 883us/step - loss: 0.3901 - accuracy: 0.8395
Epoch 88/100
800/800 [==============================] - 1s 879us/step - loss:

## Hyperparameter tuning
### GridsearchCV

In [35]:
from sklearn.model_selection import GridSearchCV

In [36]:
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units=6, kernel_initializer='uniform',
                    activation='relu', input_dim=11))
    classifier.add(Dense(units=6, kernel_initializer='uniform',
                    activation='relu'))
    classifier.add(Dense(units=1, kernel_initializer='uniform',
                    activation='sigmoid'))
    classifier.compile(optimizer=optimizer, loss='binary_crossentropy',
                       metrics=['accuracy'])
    return classifier

In [37]:
classifier = KerasClassifier(build_fn=build_classifier)

In [38]:
parameters = {'batch_size':[10, 25, 32, 72, 100,],
              'nb_epoch':[15,20,50,100],
              'optimizer':['adam', 'rmsprop']
             }

In [39]:
grid_search = GridSearchCV(estimator=classifier,
                          param_grid=parameters,
                          scoring='accuracy', cv=10)

In [40]:
grid_search = grid_search.fit(X_train, y_train)

720/720 [==============================] - 1s 896us/step - loss: 0.4836 - accuracy: 0.7968
Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
225/225 [==============================] - 0s 738us/step - loss: 0.5915 - accuracy: 0.7957


  1/225 [..............................] - ETA: 0s - loss: 0.6932 - accuracy: 0.3125WARNING:tensorflow:Callbacks method `on_train_batch_begin` is slow compared to the batch time (batch time: 0.0000s vs `on_train_batch_begin` time: 0.0010s). Check your callbacks.


800/800 [==============================] - 1s 719us/step - loss: 0.4829 - accuracy: 0.7952


In [41]:
best_parameters = grid_search.best_params_
best_parameters

{'batch_size': 10, 'nb_epoch': 50, 'optimizer': 'adam'}

In [42]:
best_score = grid_search.best_score_
best_score

0.8019999999999999